<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-DI9KG3PP" failures="1" tests="3" name="DAO" time="0.043" errors="0" timestamp="2023-03-06T22:52:41 ICT">
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.DAOTesting" name="testPrintMessage" time="0.001"/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.DAOTesting" name="testFunctionsearchCharacterGivenExistArgurment" time="0.028"/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.DAOTesting" name="testGetListCharacterDAO" time="0.036">
    <failure type="java.lang.AssertionError" message="expected [6] but found [7]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [7]
at org.teamswt301.dirverdatabasedata.dao.test.DAOTesting.testGetListCharacterDAO(DAOTesting.java:40)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- testGetListCharacterDAO -->
</testsuite> <!-- DAO -->
