<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="4" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-06T23:02:21 ICT" name="Surefire suite" finished-at="2023-03-06T23:03:14 ICT" duration-ms="53115">
    <groups>
      <group name="Delete Character">
        <method signature="CharacterCRUDNGTest.testDeleteCharacterWithGivenRightArgumentReturnWell()[pri:0, instance:org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest@6e38921c]" name="testDeleteCharacterWithGivenRightArgumentReturnWell" class="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest"/>
      </group> <!-- Delete Character -->
      <group name="Create Character">
        <method signature="CharacterCRUDNGTest.testCreateCharacterWithValues3()[pri:0, instance:org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest@6e38921c]" name="testCreateCharacterWithValues3" class="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest"/>
      </group> <!-- Create Character -->
    </groups>
    <test started-at="2023-03-06T23:02:21 ICT" name="Surefire test" finished-at="2023-03-06T23:03:14 ICT" duration-ms="53115">
      <class name="org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest">
        <test-method signature="testCreateCharacterWithValues1()[pri:0, instance:org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest@6e38921c]" started-at="2023-03-06T23:02:21 ICT" name="testCreateCharacterWithValues1" finished-at="2023-03-06T23:02:21 ICT" duration-ms="16" status="PASS">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Invalid id, id must be a number]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Invalid id, id must be a number
at org.teamswt301.databasedriver.core.CharacterCRUD.createCharacterWithValues(CharacterCRUD.java:52)
at org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest.testCreateCharacterWithValues1(CharacterCRUDNGTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateCharacterWithValues1 -->
        <test-method signature="testCreateCharacterWithValues2()[pri:0, instance:org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest@6e38921c]" started-at="2023-03-06T23:02:21 ICT" name="testCreateCharacterWithValues2" finished-at="2023-03-06T23:02:21 ICT" duration-ms="0" status="PASS">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[Invalid id, id must be a number]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: Invalid id, id must be a number
at org.teamswt301.databasedriver.core.CharacterCRUD.createCharacterWithValues(CharacterCRUD.java:52)
at org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest.testCreateCharacterWithValues2(CharacterCRUDNGTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateCharacterWithValues2 -->
        <test-method signature="testCreateCharacterWithValues3()[pri:0, instance:org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest@6e38921c]" started-at="2023-03-06T23:02:21 ICT" name="testCreateCharacterWithValues3" finished-at="2023-03-06T23:02:21 ICT" duration-ms="410" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateCharacterWithValues3 -->
        <test-method signature="testDeleteCharacterWithGivenRightArgumentReturnWell()[pri:0, instance:org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest@6e38921c]" started-at="2023-03-06T23:02:21 ICT" name="testDeleteCharacterWithGivenRightArgumentReturnWell" finished-at="2023-03-06T23:02:31 ICT" duration-ms="9437" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteCharacterWithGivenRightArgumentReturnWell -->
        <test-method is-config="true" signature="testDeleteCharacterWithGivenRightArgumentReturnWell()[pri:0, instance:org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest@6e38921c]" started-at="2023-03-06T23:02:31 ICT" name="testDeleteCharacterWithGivenRightArgumentReturnWell" finished-at="2023-03-06T23:03:14 ICT" duration-ms="43207" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1066)
at org.testng.Assert.assertEquals(Assert.java:1030)
at org.testng.Assert.assertEquals(Assert.java:1076)
at org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest.testDeleteCharacterWithGivenRightArgumentReturnWell(CharacterCRUDNGTest.java:69)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:361)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:296)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:644)
at org.testng.TestRunner.afterRun(TestRunner.java:914)
at org.testng.TestRunner.run(TestRunner.java:605)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteCharacterWithGivenRightArgumentReturnWell -->
      </class> <!-- org.teamswt301.dirverdatabasedata.dao.test.CharacterCRUDNGTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
