<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-DI9KG3PP" failures="1" tests="3" name="org.teamswt301.dirverdatabasedata.dao.test.DAOTesting" time="0.065" errors="0" timestamp="2023-03-06T22:52:41 ICT" skipped="0">
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.DAOTesting" name="testPrintMessage" time="0.001"/>
  <system-out/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.DAOTesting" name="testFunctionsearchCharacterGivenExistArgurment" time="0.028"/>
  <system-out/>
  <testcase classname="org.teamswt301.dirverdatabasedata.dao.test.DAOTesting" name="testGetListCharacterDAO" time="0.036">
    <failure message="expected [6] but found [7]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [6] but found [7]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.testng.Assert.assertEquals(Assert.java:1428)
at org.teamswt301.dirverdatabasedata.dao.test.DAOTesting.testGetListCharacterDAO(DAOTesting.java:40)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
    </failure>
  </testcase> <!-- testGetListCharacterDAO -->
  <system-out/>
</testsuite> <!-- org.teamswt301.dirverdatabasedata.dao.test.DAOTesting -->
